FileVersion = 1

[Dependencies]
"Toml-0.1.2" = "*"
corlib = "*"
"Serialize-0.1.2" = "*"
"BuildTools-0.2.2" = "*"
Click = "*"

[Project]
Name = "Grill"
TargetType = ""
StartupObject = "Grill.Program"
ProcessorMacros = []
