FileVersion = 1
Dependencies = {SyncErr = "*", Click = "*", "BuildTools-0.2.3" = "*", "Serialize-0.1.3" = "*", "Toml-0.1.3" = "*", corlib = "*", Grill = "*"}

[Project]
Name = "Grill.CLI"
StartupObject = "Grill.CLI.Program"
