FileVersion = 1

[Dependencies]
corlib = "*"
"Toml-0.1.3" = "*"
"BuildTools-0.2.3" = "*"
"Serialize-0.1.3" = "*"
Click = "*"

[Project]
Name = "Grill"
TargetType = ""
StartupObject = "Grill.Program"
ProcessorMacros = []
