FileVersion = 1
Dependencies = {corlib = "*", Grill = "*", Click = "*", SyncErr = "*"}

[Project]
Name = "Grill.CLI"
StartupObject = "Grill.CLI.Program"

[Configs.Debug.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(WorkspaceDir)/resources\",\"$(TargetDir)\")"]
