FileVersion = 1

[Dependencies]
corlib = "*"
Grill = "*"
Click = "*"
SyncErr = "*"

[Project]
Name = "Grill.CLI"
TargetType = "BeefConsoleApplication"
StartupObject = "Grill.CLI.Program"

[Configs]

[Configs.Debug]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyFilesIfNewer(\"$(WorkspaceDir)/resources\",\"$(TargetDir)\")"]
