FileVersion = 1

[Dependencies]
"Serialize-0.1.3" = "*"
corlib = "*"
"Toml-0.1.3" = "*"

[Project]
Name = "testproj"
TargetType = "BeefConsoleApplication"
StartupObject = "testproj.Program"
ProcessorMacros = []
